# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Gone 个人知识积累
email: gz5@qq.com
description: > # this means to ignore newlines until "baseurl:"
        James Gone blog on github.
        About my konwledge. 技术知识记录和分享。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: james-gone 

# Build settings
markdown: kramdown

timezone: Asia/Hong_Kong


